### ISSUE TITLE
Error response from daemon: unauthorized

### ISSUE THREAD

**Issue by odinson394** [Zibbp/Spotify-to-Deezer#1]
Hi there, 

Probably this is down to me not really knowing what I'm doing here, but if I follow the instructions in the README (so (1) Save a copy of the `docker-compose.yml` file; (2+3) set-up applications for Spotify and Deezer; (4) set-up docker-compose.yml with the Spotify and Deezer ID's and secret keys; (5) run docker-compose run spotify2deezer node main.js login), then docker throws this error: 

> Error response from daemon: Head "https://ghcr.io/v2/zibbp/spotify-to-deezer/manifests/latest": unauthorized

I've looked up the error online and tried to figure it out but haven't been able to resolve it. Seems I need to include some GitHub credentials to access the file?

I understand this is not a helpdesk, so if I'm asking a question where the solution is painfully obvious to most people, please just point me in the direction of some generic materials to read if you'd be so kind.

JQ

**Comment by Zibbp** [comment]
Hi, the image was marked as private from some unknown reason on Github's container registry. I made it public so you should be able to pull and run the container now. Let me know if you face any more issues.

**Comment by odinson394** [comment]
Hi Isaac,

Thanks, I’m able to pull it in now. I’ll continue setting up later today/this evening. Thanks!

Eduard
