### ISSUE TITLE
redirect_uri

### ISSUE THREAD

**Issue by odinson394** [Zibbp/Spotify-to-Deezer#2]
When prompted I navigated to the URL:

https://connect.deezer.com/oauth/auth.php?app_id=[MYAPPID]&redirect_uri=http://localhost:5000/callback&perms=manage_library,offline_access

First I land on a 'Welcome Back' page specifying as which user I am logged in. If I then hit continue, connect.deezer.com throws an error: 

<img width="976" alt="Screenshot 2022-04-19 at 14 13 06" src="https://user-images.githubusercontent.com/46132255/164001743-a768636c-fd02-46fd-82b5-f621cb7ac4d7.png">

My redirect URL is set to http://localhost:5000, as per the README. I'm running macOS Monterey on an M1.

**Comment by Zibbp** [comment]
Can you try setting the Redirect URL in the Deezer developer app to `http://localhost:5000/callback`.

**Comment by odinson394** [comment]
Hi,

Changing to 'http://localhost:5000/callback' gets me a different error message: 

'Firefox can’t establish a connection to the server at localhost:5000'

Similar message for Safari. I did read something about macOS Monterey using port 5000 for AirPlay Receiver so I deactivated that. I'm not running any security software, and have tried switching the built-in firewall off as well to see if that might have been blocking something. 

However, no luck so far.

JQ

**Comment by Zibbp** [comment]
It should error out as the login container is not opening a webserver for the callback to connect to. Take the link you received `localhost:5000/callback?code=1234` and paste it in the terminal where it's asking for the Authentical URL/Callback URL and it should return the access token.
![image](https://user-images.githubusercontent.com/21207065/164086118-ffccbd1d-9c47-47dd-8778-8965bcc5a17a.png)

It's not as clean as a webserver but this way no server is needed and no ports need to be opened.

**Comment by odinson394** [comment]
Hi, 

OK got the token, thanks! I'm running into a separate issue but will post a new one.

Best,

JQ
