### ISSUE TITLE
Invalid playlist ID

### ISSUE THREAD

**Issue by odinson394** [Zibbp/Spotify-to-Deezer#3]
When I run docker-compose-up, at first the program did not locate any playlists:

> Attaching to spotify2deezer
> spotify2deezer  | Authenticated with Spotify.
> spotify2deezer  | Reading Spotify playlists.
> spotify2deezer  | Found 0 Spotify playlists.
> spotify2deezer exited with code 0
> 

I was using the following data in the spotify-playlists.txt (I changed a digit or two here):

> 4KC7IU0vSEBp7mmenZIRu7,Sing,yMSjekcmaZQVk1US9

To see if it might make a difference, I added the same playlist a second time, like so: 

> 
> 4KC7IU0vSEBp7mmenZIRu7,Sing,yMSjekcmaZQVk1US9
> 4KC7IU0vSEBp7mmenZIRu7,Sing,yMSjekcmaZQVk1US9

At that point, I get an Invalid Playlist ID error: 

> spotify2deezer  | Authenticated with Spotify.
> spotify2deezer  | Reading Spotify playlists.
> spotify2deezer  | Found 1 Spotify playlists.
> spotify2deezer  | Fetching tracks for playlist undefined
> spotify2deezer  | /opt/app/node_modules/spotify-web-api-node/src/http-manager.js:39
> spotify2deezer  |     return new WebapiRegularError(response.body, response.headers, response.statusCode);
> spotify2deezer  |            ^
> spotify2deezer  | 
> spotify2deezer  | WebapiRegularError: An error occurred while communicating with Spotify's Web API.
> spotify2deezer  | Details: Invalid playlist Id.
> spotify2deezer  |     at _toError (/opt/app/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
> spotify2deezer  |     at /opt/app/node_modules/spotify-web-api-node/src/http-manager.js:71:25
> spotify2deezer  |     at Request.callback (/opt/app/node_modules/superagent/lib/node/index.js:905:3)
> spotify2deezer  |     at /opt/app/node_modules/superagent/lib/node/index.js:1127:20
> spotify2deezer  |     at IncomingMessage.<anonymous> (/opt/app/node_modules/superagent/lib/node/parsers/json.js:22:7)
> spotify2deezer  |     at Stream.emit (node:events:526:28)
> spotify2deezer  |     at Unzip.<anonymous> (/opt/app/node_modules/superagent/lib/node/unzip.js:53:12)
> spotify2deezer  |     at Unzip.emit (node:events:526:28)
> spotify2deezer  |     at endReadableNT (node:internal/streams/readable:1345:12)
> spotify2deezer  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
> spotify2deezer  |   body: { error: { status: 404, message: 'Invalid playlist Id' } },
> spotify2deezer  |   headers: {
> spotify2deezer  |     'content-type': 'application/json; charset=utf-8',
> spotify2deezer  |     'cache-control': 'private, max-age=0',
> spotify2deezer  |     'x-robots-tag': 'noindex, nofollow',
> spotify2deezer  |     'access-control-allow-origin': '*',
> spotify2deezer  |     'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
> spotify2deezer  |     'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
> spotify2deezer  |     'access-control-allow-credentials': 'true',
> spotify2deezer  |     'access-control-max-age': '604800',
> spotify2deezer  |     'content-encoding': 'gzip',
> spotify2deezer  |     'strict-transport-security': 'max-age=31536000',
> spotify2deezer  |     'x-content-type-options': 'nosniff',
> spotify2deezer  |     date: 'Wed, 20 Apr 2022 15:18:14 GMT',
> spotify2deezer  |     server: 'envoy',
> spotify2deezer  |     via: 'HTTP/2 edgeproxy, 1.1 google',
> spotify2deezer  |     'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
> spotify2deezer  |     connection: 'close',
> spotify2deezer  |     'transfer-encoding': 'chunked'
> spotify2deezer  |   },
> spotify2deezer  |   statusCode: 404
> spotify2deezer  | }
> spotify2deezer exited with code 1

I'm not sure what I'm doing wrong, or whether it might be a privacy setting or something like that. Setting the playlist to collaborative did not resolve the issue. Thanks for all the help 🥇 .

Best,

JQ

**Comment by Zibbp** [comment]
Do you have the headers in the .txt file? I should clean up the readme and strengthen some points. The spotify-playlists.txt file should like like the following, including the heading names (id, name, etc). The playlist needs to be public as Spotify is not authenticating under your account but using a general authentication method with no permissions to your private playlists.

```
id,name,deezerPlaylistId
79QHayucQm6M4wUlUbhQNQ,METALCORE,100151112489
```

I also see that you're third column doesn't look like a Deezer playlist ID which is just an integer. Not sure if you changed it for privacy reasons or not.

**Comment by odinson394** [comment]
Hi, 

That resolved it, I was missing the header indeed and Deezer needed to be an integer. Now it's working like a charm, much appreciated. Great that you wrote this, was exactly what I was looking for :).

Not sure if your README is the issue as much as my pretty basic skill level here!

JQ
